get_pods:
	kubectl get pods --show-labels

kubectl_logs:
	kubectlectl logs <name>

kubectl_describe:
	 kubectlectl describe pod <name?

scale_down:
	kubectl scale deployment energy-app-deployment --replicas=0